<?php

return [
    ''                         => 'Please Select A Provider',
    '@message.alltel.com'      => 'Alltel',
    '@txt.att.net'             => 'AT&T',
    '@txt.bell.ca'             => 'Bell Mobility',
    '@cingularme.com'          => 'Cingular',
    '@fido.ca'                 => 'Fido',
    '@msg.koodomobile.com'     => 'Kudo Mobile',
    '@mymetropcs.com'          => 'Metro PCS',
    '@text.mtsmobility.com'    => 'MTS',
    '@messaging.nextel.com'    => 'Nextel',
    '@ptel.com'                => 'Powertel',
    '@txt.bell.ca'             => 'President’s Choice',
    '@qwestmp.com'             => 'Qwest',
    '@pcs.rogers.com'          => 'Rogers Wireless',
    '@sms.sasktel.com'         => 'Sasktel',
    '@messaging.sprintpcs.com' => 'Sprint',
    '@txt.bell.ca'             => 'Solo',
    '@tms.suncom.com'          => 'Suncom',
    '@msg.telus.com'           => 'Telus',
    '@vmobile.ca'              => 'Virgin',
    '@tmomail.net'             => 'T-Mobile',
    '@vtext.com'               => 'Verizon',
    '@vmobl.com'               => 'Virgin Mobile',
    '@email.uscc.net'          => 'U.S. Cellular',
];